# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmallAchievements' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmallAchievements

	pod 'R.swift'
 	pod 'Firebase/Core'
  	pod 'Firebase/Auth'
 	pod 'Firebase/Database'
  	pod 'Firebase/Functions'
  	pod 'Firebase/Firestore'
  	pod 'Firebase/Messaging'
  	pod 'Firebase/Analytics'
end
